-- Baseline schema for API Mediway.
--
-- Captured from a schema generated by Hibernate (ddl-auto=create) against a disposable
-- MySQL 8.0 instance running the entities as they exist as of this migration, so it
-- matches exactly what `ddl-auto=validate` will check for at startup.
--
-- FOREIGN_KEY_CHECKS is disabled while creating tables because some tables reference
-- each other in a non-linear order (e.g. tb_patients_info <-> tb_doctors <-> tb_caregivers_info).
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `tb_users` (
  `user_id` binary(16) NOT NULL,
  `email` varchar(255) NOT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `number` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `UKgrd22228p1miaivbn9yg178pm` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_roles` (
  `role_id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_user_roles` (
  `role_id` bigint NOT NULL,
  `user_id` binary(16) NOT NULL,
  PRIMARY KEY (`role_id`,`user_id`),
  KEY `FKugolgxur3og4u4y8od79ubp6` (`user_id`),
  CONSTRAINT `FK3mxrxqo67aefq0yaufnn84v3e` FOREIGN KEY (`role_id`) REFERENCES `tb_roles` (`role_id`),
  CONSTRAINT `FKugolgxur3og4u4y8od79ubp6` FOREIGN KEY (`user_id`) REFERENCES `tb_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_doctors` (
  `doctor_info_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` binary(16) NOT NULL,
  `crm` varchar(255) DEFAULT NULL,
  `specialty` varchar(255) DEFAULT NULL,
  `availability` enum('INTEGRAL','PARCIAL_MANHA','PARCIAL_TARDE','PLANTOES') NOT NULL,
  PRIMARY KEY (`doctor_info_id`),
  UNIQUE KEY `UKpi70gwy4xgms85xyr16aee5ih` (`user_id`),
  UNIQUE KEY `UKfsbehevol90n6w4naruhpac9e` (`crm`),
  CONSTRAINT `FKgg6upu8f9962swyhnvpieimit` FOREIGN KEY (`user_id`) REFERENCES `tb_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_caregivers_info` (
  `caregiver_info_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` binary(16) NOT NULL,
  `experience` varchar(500) DEFAULT NULL,
  `specialty` varchar(255) DEFAULT NULL,
  `availability` enum('INTEGRAL','PARCIAL_MANHA','PARCIAL_TARDE','PLANTOES') NOT NULL,
  PRIMARY KEY (`caregiver_info_id`),
  UNIQUE KEY `UKg4mg3v0wnouaipt9t7nw0gqub` (`user_id`),
  CONSTRAINT `FKrlkmsu6micu9dasvhw2damd7m` FOREIGN KEY (`user_id`) REFERENCES `tb_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_patients_info` (
  `age` int DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `caregiver_id` bigint DEFAULT NULL,
  `doctor_id` bigint DEFAULT NULL,
  `patient_info_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` binary(16) NOT NULL,
  `condition_patient` varchar(255) DEFAULT NULL,
  `gender_patient` enum('FEMININO','MASCULINO','NAO_INFORMADO') DEFAULT NULL,
  `status_patient` enum('EM_ACOMPANHAMENTO','ESTAVEL','NESSECITA_DE_ATENCAO','REABILITACAO') DEFAULT NULL,
  PRIMARY KEY (`patient_info_id`),
  UNIQUE KEY `UKohri7prhb7ha0iq9txdanxk52` (`user_id`),
  KEY `FK8v45hnd72mb1cdbf3sxp37gjo` (`doctor_id`),
  KEY `FKgk7wdl7262yat1b5d8kc8v0n0` (`caregiver_id`),
  CONSTRAINT `FK8v45hnd72mb1cdbf3sxp37gjo` FOREIGN KEY (`doctor_id`) REFERENCES `tb_doctors` (`doctor_info_id`),
  CONSTRAINT `FKgk7wdl7262yat1b5d8kc8v0n0` FOREIGN KEY (`caregiver_id`) REFERENCES `tb_caregivers_info` (`caregiver_info_id`),
  CONSTRAINT `FKsrmfh53bbcar97mp14r24u11m` FOREIGN KEY (`user_id`) REFERENCES `tb_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_medicine_box` (
  `medicine_box_id` bigint NOT NULL AUTO_INCREMENT,
  `patient_id` bigint NOT NULL,
  `nome` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`medicine_box_id`),
  UNIQUE KEY `UK1nu99gyq4f9rvmad5a3ukybdp` (`patient_id`),
  CONSTRAINT `FK6l8ix28ha93a5a3wuvpfjryam` FOREIGN KEY (`patient_id`) REFERENCES `tb_patients_info` (`patient_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_medications` (
  `estoque` int DEFAULT NULL,
  `hora` time DEFAULT NULL,
  `medication_id` bigint NOT NULL AUTO_INCREMENT,
  `medicine_box_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `descricao` varchar(500) DEFAULT NULL,
  `concentracao` varchar(255) DEFAULT NULL,
  `gaveta` varchar(255) DEFAULT NULL,
  `nome` varchar(255) NOT NULL,
  `nome_referencia` varchar(255) DEFAULT NULL,
  `quantidade` varchar(255) DEFAULT NULL,
  `dias` json DEFAULT NULL,
  `status` enum('ATIVO','SUSPENSO') DEFAULT NULL,
  `tipo` enum('FITOTERAPICO','GENERICO','MANIPULADO','OUTRO','REFERENCIA','SIMILAR') NOT NULL,
  PRIMARY KEY (`medication_id`),
  KEY `FKffc72nft49hvp60wbltvok6t5` (`medicine_box_id`),
  KEY `FK5fjk5flwb24mj7tsjmparf6vd` (`patient_id`),
  CONSTRAINT `FK5fjk5flwb24mj7tsjmparf6vd` FOREIGN KEY (`patient_id`) REFERENCES `tb_patients_info` (`patient_info_id`),
  CONSTRAINT `FKffc72nft49hvp60wbltvok6t5` FOREIGN KEY (`medicine_box_id`) REFERENCES `tb_medicine_box` (`medicine_box_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_consultations` (
  `consultation_date` date DEFAULT NULL,
  `consultation_time` time DEFAULT NULL,
  `consultation_id` bigint NOT NULL AUTO_INCREMENT,
  `doctor_id` bigint NOT NULL,
  `patient_id` bigint NOT NULL,
  `request_date` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `local_consultation` varchar(255) DEFAULT NULL,
  `requeriments` varchar(255) DEFAULT NULL,
  `status` enum('CANCELADO','INDEFERIDO','MARCADO','NAO_COMPARECEU','REALIZADO','REMARCADO') DEFAULT NULL,
  PRIMARY KEY (`consultation_id`),
  KEY `FKe9ve55pq8oi951ccc7bta90gm` (`doctor_id`),
  KEY `FKmhps7hbmxa2048qd3eab16f00` (`patient_id`),
  CONSTRAINT `FKe9ve55pq8oi951ccc7bta90gm` FOREIGN KEY (`doctor_id`) REFERENCES `tb_doctors` (`doctor_info_id`),
  CONSTRAINT `FKmhps7hbmxa2048qd3eab16f00` FOREIGN KEY (`patient_id`) REFERENCES `tb_patients_info` (`patient_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_exams` (
  `cancellation_date` date DEFAULT NULL,
  `exam_date` date DEFAULT NULL,
  `exam_time` time DEFAULT NULL,
  `exam_id` bigint NOT NULL AUTO_INCREMENT,
  `patient_id` bigint NOT NULL,
  `request_date` datetime(6) DEFAULT NULL,
  `local` varchar(255) DEFAULT NULL,
  `requeriments` varchar(255) DEFAULT NULL,
  `type_exam` varchar(255) DEFAULT NULL,
  `status` enum('CANCELADO','INDEFERIDO','MARCADO','NAO_COMPARECEU','REALIZADO','REMARCADO') DEFAULT NULL,
  PRIMARY KEY (`exam_id`),
  KEY `FKbma873b1j04o3hm9a0lc71luf` (`patient_id`),
  CONSTRAINT `FKbma873b1j04o3hm9a0lc71luf` FOREIGN KEY (`patient_id`) REFERENCES `tb_patients_info` (`patient_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_vaccines` (
  `manufacture_date` date DEFAULT NULL,
  `next_dose_date` date DEFAULT NULL,
  `patient_id` bigint NOT NULL,
  `vaccination_date` datetime(6) DEFAULT NULL,
  `vaccine_id` bigint NOT NULL AUTO_INCREMENT,
  `lote` varchar(255) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `dose_type` enum('PRIMEIRA_DOSE','REFORCO','SEGUNDA_DOSE','UNICA_DOSE') NOT NULL,
  `status` enum('AGENDADA','APLICADA','ATRASADA') NOT NULL,
  PRIMARY KEY (`vaccine_id`),
  KEY `FKjm8up2usn6m0tyvuykjvobe9f` (`patient_id`),
  CONSTRAINT `FKjm8up2usn6m0tyvuykjvobe9f` FOREIGN KEY (`patient_id`) REFERENCES `tb_patients_info` (`patient_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_password_reset_code` (
  `used` bit(1) NOT NULL,
  `code_id` bigint NOT NULL AUTO_INCREMENT,
  `expiration` datetime(6) DEFAULT NULL,
  `user_id` binary(16) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`code_id`),
  KEY `FK2mjc54iwmd9ct0o12417tfytp` (`user_id`),
  CONSTRAINT `FK2mjc54iwmd9ct0o12417tfytp` FOREIGN KEY (`user_id`) REFERENCES `tb_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;